### ISSUE TITLE
V2 rollout

### ISSUE THREAD

**Issue by mkobetic** [xmtp/xmtp-js#178]
V2 refers to a planned switch to "negotiated topics" that will enhance message and conversation privacy and allow carrying multiple independent conversations between parties.

# V2 Implementation
This just adds the support for all these things without actually employing them anywhere
* [x] signed keys and bundles #159, #166, #175, #176
* [x] invitations #177
* [x] message v2 #185

At this point there are no changes on the network, everything runs in v1 mode

# V1/V2 Transition
* [x] dual v1/v2 private key bundle support in the Client (based on V1 published bundles) #185
* [x] dual v1/v2 messaging support applied based on the version of the recipient's contact bundle #185
* [x] 2022-11-02 release v7.0.0 #208
* [x] 2022-11-08 release v7.1.0 #204
* [x] 2023-01-01 deprecate pre-v7.0.0 SDK 
* [ ] convert all contacts to v2

At this point we'll start seeing v2 activity on the network, v1 should slowly decrease as clients upgrade and users engage.
We need to get all the users to republish their contact bundles as v2 so that majority of new activity is v2. We might be able to do this ourselves (when all clients are upgraded), since we don't need the wallet for the v1->v2 contact bundle conversion. Some level of V1 activity will remain as pre-existing V1 conversations will continue, unless the participants explicitly start a new V2 conversation.

# V1 Deprecation
* [ ] start publishing V2 private key bundles

We will have to be careful here, users new to the platform that don't have any pre-existing conversations should be able to get by with native V2 keys only. However users that have pre-existing V1 conversation will have to keep using "V1 compatible" key bundles (i.e. bundles generated as V1 and converted to V2). Otherwise they won't be able to resume their pre-existing V1 conversations (see #222).

# V1 Cleanup

It's not clear at this point whether there will be anything to clean up. At this point we intend to maintain pre-existing V1 conversations going forward.

**Comment by mkobetic** [comment]
In order to proceed with the rollout plan we need to get clients to version at least v6.4.0 in order for clients to be able to tolerate/ignore v2 contact bundles being published into contact topics (#166 has the fix).

We have a pending deprecation related to sunsetting the waku/libp2p based client interface on the node (in favor of the new GRPC based interface). The deadline we set is November 8th.

> “On November 8th, we plan to sunset the legacy APIs that power versions of the SDK < 6.0.0.“

It would probably be best if we revised that deprecation plan to require at least v6.4.0. The consequences of that revision should be relatively minor as v6.4.0 should be fully backward compatible with v6.0.0. The biggest irritant would probably be if someone already did the work to upgrade to 6.0.0 and was hoping to be done for next little while. But again the additional effort should be rather minimal.

Here's what we could say as possible explanation/justification:

v6.4.0 includes a fix that allows clients to tolerate rollout of v7 that introduces a major protocol upgrade (more details about V2 here). More specifically V2 clients will start publishing an updated version of their contact bundles. If a pre v6.4.0 client attempts to read a contact topic of a peer that published a V2 bundle it will fail decoding it and become unable to communicate with that peer. The fix allows the client to ignore the V2 contact and continue the search for a V1 contact. The rest of the V2 activity on the network will be invisible to pre v7 clients. v7 clients will be able to communicate with pre-v7 clients using V1 of the protocol.

We will provide additional transition period before deprecating pre-v7 sdk versions, but we need to push for the v6.4.0 version relatively quickly in order to be able to start the transition period. The effort to upgrade to v6.4.0 instead of v6.0.0 should be very similar as v6.4.0 should be fully backward compatible with v.6.0.0.

**Comment by mkobetic** [comment]
Turns out I was wrong and we don't really have to get everyone on v6.4.0 before continuing with the rollout. The thing I missed with #166 is that it also changes the direction in which we read the contact bundles (we only read the oldest bundle prior to #166), so the older clients shouldn't be impacted by newer contact bundles being published. So the rollout can continue as we see fit.

**Comment by mkobetic** [comment]
After we make v7 release official, we need to set deprecation date for pre-v7 versions of the SDK in order to be able to proceed with this rollout plan. As we discussed on our engineering sync, we don't have to wait as long as we did for pre-v6 deprecation (which was intended to be aligned with ETH SF). We didn't make any decision so I'm going to propose that we set the date to:
```
A month after we make the v7 announcement
```
@saulmc @xmtp/engineering does that sound reasonable?

**Comment by saulmc** [comment]
@mkobetic It does sound reasonable. Thank you for thinking this through!
