### ISSUE TITLE
Tracking: XMTP v3 Alpha

### ISSUE THREAD

**Issue by m-005** [xmtp/xmtp-js#340]
Alpha stage of [XMTP v3](https://www.notion.so/xmtplabs/XMTP-v3-e626efd31be7408a941cad15897a7b3b?pvs=4) which is themed around privacy and security features

[XMTP v3 Checklist](https://www.notion.so/xmtplabs/XMTP-v3-Alpha-Checklist-4340c93d8161439884d3d86b4708f8a8?pvs=4) (to be updated based on GitHub Board throughout the quarter for recording OKR progress)

```[tasklist]
### Tasks
- [ ] https://github.com/xmtp/xmtp-js/issues/341
- [ ] https://github.com/xmtp/xmtp-js/issues/342
- [ ] https://github.com/xmtp/xmtp-js/issues/344
- [ ] #343
```

**Comment by rygine** [comment]
closing this in favor of the project board: https://github.com/orgs/xmtp/projects/11
