### ISSUE TITLE
Tracking: Implement double-ratchet using vodozemac (codename: voodoo)

### ISSUE THREAD

**Issue by m-005** [xmtp/xmtp-js#342]
```[tasklist]
### Tasks
- [ ] https://github.com/xmtp/xmtp-js/issues/345
- [ ] https://github.com/xmtp/xmtp-js/issues/346
- [ ] https://github.com/xmtp/xmtp-js/issues/347
- [ ] https://github.com/xmtp/xmtp-js/issues/348
- [ ] https://github.com/xmtp/xmtp-js/issues/350
- [ ] https://github.com/xmtp/xmtp-js/issues/351
- [ ] https://github.com/xmtp/xmtp-js/issues/352
- [ ] https://github.com/xmtp/xmtp-js/issues/349
```

**Comment by rygine** [comment]
we are using MLS instead of double ratchet.

see: https://github.com/orgs/xmtp/projects/11
