### ISSUE TITLE
Tracking: Potential Alpha Items

### ISSUE THREAD

**Issue by m-005** [xmtp/xmtp-js#344]
```[tasklist]
### Tasks
- [ ] https://github.com/xmtp/xmtp-js/issues/353
- [ ] https://github.com/xmtp/xmtp-js/issues/354
- [ ] https://github.com/xmtp/xmtp-js/issues/355
- [ ] https://github.com/xmtp/xmtp-js/issues/356
- [ ] https://github.com/xmtp/xmtp-js/issues/357
- [ ] https://github.com/xmtp/xmtp-js/issues/358
- [ ] https://github.com/xmtp/xmtp-js/issues/360
- [ ] https://github.com/xmtp/xmtp-js/issues/359
- [ ] https://github.com/xmtp/xmtp-js/issues/366
- [ ] https://github.com/xmtp/xmtp-js/issues/361
- [ ] https://github.com/xmtp/xmtp-js/issues/362
- [ ] https://github.com/xmtp/xmtp-js/issues/363
- [ ] https://github.com/xmtp/xmtp-js/issues/364
- [ ] https://github.com/xmtp/xmtp-js/issues/365
```
