### ISSUE TITLE
Tracking: Group Chat

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-js#553]
### Group Chat

Should mimic functionality found for groups in iOS, Android, and RN.

- [ ] Reproduce utility classes/methods
  - [ ] Client
    - [ ] update existing `create` method on client to also create a `FfiXmtpClient`
    - [ ] Existing client should now also have a `FfiLogger`
    - [ ] Have existing SigningKey extend `FfiInboxOwner` so it can be used to create both V2 and V3 clients
    - [ ] If `FfiXmtpClient` exists get address from `account_address()`
    - [ ] If `FfiXmtpClient` exists store a reference to `installation_id()`
    - [ ] Conversations on client should also take a `libXMTPConversations`
    - [ ] If `FfiXmtpClient` exists client create should call `register_identity`
    - [ ] Ability to `list_my_installations()`
    - [ ] Ability to `revoke_installation()`
  - [ ] Conversations
    - [ ] Should be able to create a group `newGroup()` -- `create_group()`
    - [ ] Should be able to list just groups `listGroups` -- `libXMTPConversations.list()`
    - [ ] Should be able to list an ordered list of conversations & groups `list(includeGroups: Boolean = false)`
    - [ ] Should be able to stream groups `libXMTPConversations.stream()`
    - [ ] Should be able to stream both conversations & groups `stream(includeGroups:Boolean = false)`
    - [ ] Should be able to `sync` groups so that the libxmtp database gets updated
    - [ ] Should be able to stream all messages from both groups and conversations (`streamAllMessages(includeGroups: Boolean = false)`
  - [ ] Conversation/Group methods
    - [ ] Should have a unique identifier of the conversation `id()` equivalent to existing topic
    - [ ] Should be able to `send()` messages of any content type
    - [ ] Should be able to resync the libxmtp database `sync()`
    - [ ] Should be able to list messages `find_messages()` as Decoded and Decrypted Messages
    - [ ] Should be able to list members `list_members()`
    - [ ] Should be able to add members `add_members()`
    - [ ] Should be able to remove members `remove_members()`
    - [ ] Should be able to stream messages `stream()`
    - [ ] Should be able to leave a group `leave()`
    - [ ] Can check if a message can be sent `can_message()`
    - [ ] Should be able to block or allow a group by id
    - [ ] Should be able to set a group chat name
    - [ ] Should be able to receive push notifications for a group chat
    - [ ] Should be able to see who added me to a group
    - [ ] Should be able to see if the group `is_active`

### Nice to have

- [ ] Create sample app
    - [ ] Use SDK to demonstrate
        - [ ] Group Chat
          - [ ] send messages (any content type)
          - [ ] add member
          - [ ] remove member
          - [ ] list members
          - [ ] leave
