### ISSUE TITLE
Tracking: Node SDK - (Group Chat)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-js#607]
### MVP

- [x] create a v3 client
- [x] can_message
- [x] stream groups
- [x] stream all group messages
- [x] stream all messages in a group
- [x] sync group
- [x] sync groups
- [x] send message to group
- [x] check to see if still active in group
